In [67]:
!pip install numpy

In [68]:
import numpy as np

In [69]:
a = np.array([1, 2, 3, "a"])

In [70]:
a #here it is containing the homogenious data type

array(['1', '2', '3', 'a'], dtype='<U21')

In [71]:
a = np.array([1, 2, 3, "a", {1:2}])

In [72]:
a #here its returns the object when passing the diff data types

array([1, 2, 3, 'a', {1: 2}], dtype=object)

In [73]:
a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]]])

In [74]:
print('a dimension : ', a.ndim) #here we using the ndim attribute to get the array dimensions.
print('b dimension : ', b.ndim)
print('c dimension : ', c.ndim)
print('d dimension : ', d.ndim)

a dimension :  0
b dimension :  1
c dimension :  2
d dimension :  3


In [75]:
print(a)      # here we use shape attribute to get the array shape
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
shape of d: (2, 2, 3)


In [76]:
print(c.dtype)  #here we use dtype attribute to know the element which data type  is used in the array
print(d.dtype)

int64
int64


In [77]:
print(type(a))    # here we use type class to know the which type of object it is.
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [78]:
print(len(d))
print(len(b))


2
3


In [79]:
#here by using arange() function to create an array(1 dimensional).
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
np.arange(1,11,3) #(start, stop, step)

array([ 1,  4,  7, 10])

In [81]:
np.eye(5, dtype=int)  #by using eye it create 2dimensional array with value 1
# here 5 means rows and columns

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [82]:
np.zeros((5,5), dtype=int) #by using zeros it create 2dimensional array with full of zeros(0).
# here 5 means rows and columns

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [83]:
np.ones((5,5), dtype=int) #by using ones it create 2dimensional array with full of ones(1).
# here (5,5) means rows and columns

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [84]:
np.full((4,4),7,dtype=int) #by using full it create 2dimensional array with full of 7.
# here (5,5) means rows and columns 7 means, array full 7 values

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [85]:
x=[1,2,3,4,5,6,7,8,9]
np.diag(x)  #here we use diag, it will create the array with the size of list(9x9) along with the diagonal list values.

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [86]:
x = np.arange(1,17)
print(x)
print(x.ndim)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1
(16,)


In [87]:
n = x.reshape((4,4))
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
2


In [88]:
n1 = x.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [89]:
v=n.ravel() #here we use ravel it will convert the array into 1 dimensional array(if the array was 2D or 3D)
print(v)
print(v.shape)
print(v.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [90]:
v=n.flatten() #here we use flatten it will convert the array into 1 dimensional array(if the array was 2D or 3D)
print(v)
print(v.shape)
print(v.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [91]:
a= np.arange(2,17,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [92]:
print(a[2])
print(a[2:5])

6
[ 6  8 10]


In [93]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
x2 = x1   #view or assign

In [95]:
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [96]:
x2[0] = 10

In [97]:
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [98]:
print(id(x1))
print(id(x2))   #Both variable are shares memory
#use numpy shares_memory function to check both xi and x2 shares a memory

132587036830256
132587036830256


In [99]:
print(np.shares_memory(x1, x2))

True


In [100]:
x3 = x1.view()

In [101]:
np.shares_memory(x1, x3)

True

In [102]:
x3[0] =100

In [103]:
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [104]:
x4 = np.copy(x1)

In [105]:
x4[-1] =900

In [106]:
print(x1) #here your original array didn't get changed on change of its copy (x4)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [107]:
a


array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [108]:
a>3

array([False,  True,  True,  True,  True,  True,  True,  True])

In [109]:
x1 == x4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [110]:
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
print(n.transpose())

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [112]:
np.hstack((x1, x4))   #here we use hstack function means horizontal concatination.

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

In [113]:
a=[11,12,13]
b=[21,22,23]
print(a+b)    #here we can observe the list concatination.

[11, 12, 13, 21, 22, 23]


In [114]:
print(x1)
print(x4)
np.insert(x1, 5, x4)  #by using insert() we can add the array from where it wants(by giving position.)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3,   4, 100,   1,   2,   3,   4,   5,   6,   7,
         8, 900,   5,   6,   7,   8,   9])

In [115]:
print(x2)
np.delete(x2, 2)    #by using delete() we can delete the elements by passing the index values of an array.

[100   1   2   3   4   5   6   7   8   9]


array([100,   1,   3,   4,   5,   6,   7,   8,   9])

In [116]:
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [117]:
np.sin(a)   #here we declare an array and passing mathematical operations
#it gives the sin values for the given array.

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [118]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [119]:
print((np.cos(a))/(np.sin(a)))

[[ 0.64209262 -0.45765755 -7.01525255]
 [ 0.86369115 -0.29581292 -3.436353  ]
 [ 1.14751542 -0.14706506 -2.21084541]]


In [120]:
np.exp(a)   #here we use exponential value of a

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [121]:
np.sum(a)   #here we use sum() on an array

np.int64(45)

In [122]:
np.sum(a, axis=0)   #sum in array a column wise

array([12, 15, 18])

In [123]:
np.sum(a, axis=1)   #sum in array a row wise

array([ 6, 15, 24])

In [124]:
print(np.median(a)) #we can apply the statistial values

5.0


In [125]:
print(np.mean(a))   #we can apply the statistial values

5.0


In [126]:
np.std(a)

np.float64(2.581988897471611)

In [127]:
np.max(a)

np.int64(9)

In [128]:
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 900])

In [129]:
arr = np.array([[12, 13, 15, 17, 19, 29, 24, 11, 9, 25,27]])
arr1 = np.where(arr>17)
print(arr1)   #here we use the where method with some codition
#it will return the values of array indexing.

(array([0, 0, 0, 0, 0]), array([ 4,  5,  6,  9, 10]))


In [130]:
print(dir(list)) #by using the dir function we get list metods by passing list class in the function

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [131]:
print(dir(set))   #by using the dir function we get set metods by passing set class in the function

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']
